apiVersion: v1
kind: ReplicationController
metadata:
 name: myngpod
spec:
 replicas: 5
 template:
  metadata:
   labels:
    app: development
  spec:
   containers:
    - image: nginx
      name: ngcontroller
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
           path: /index.html
           port: 80
